### ISSUE TITLE
App Crash after pressing lend out to...

### ISSUE THREAD

**Issue by frieda21** [tfonteyn/NeverTooManyBooks#70]
App Crash after pressing lend out to...
Crash report:
```
{"STACK_TRACE":"java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.Comparable.compareTo(java.lang.Object)' on a null object reference\n\tat java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:320)\n\tat java.util.ComparableTimSort.sort(ComparableTimSort.java:202)\n\tat java.util.Arrays.sort(Arrays.java:1128)\n\tat java.util.Arrays.sort(Arrays.java:1334)\n\tat java.util.ArrayList.sort(ArrayList.java:1738)\n\tat java.util.Collections.sort(Collections.java:210)\n\tat java.util.Collections.sort(Collections.java:163)\n\tat h3.s.a(Unknown Source:109)\n\tat h3.s.f(Unknown Source:40)\n\tat g3.a.onViewCreated(Unknown Source:62)\n\tat h3.r.onViewCreated(Unknown Source:0)\n\tat androidx.fragment.app.I.performViewCreated(Unknown Source:14)\n\tat androidx.fragment.app.s0.f(Unknown Source:298)\n\tat androidx.fragment.app.s0.k(Unknown Source:174)\n\tat androidx.fragment.app.j0.B(Unknown Source:1121)\n\tat androidx.fragment.app.j0.W(Unknown Source:91)\n\tat androidx.fragment.app.j0.z(Unknown Source:78)\n\tat androidx.fragment.app.s.run(Unknown Source:10)\n\tat android.os.Handler.handleCallback(Handler.java:958)\n\tat android.os.Handler.dispatchMessage(Handler.java:99)\n\tat android.os.Looper.loopOnce(Looper.java:230)\n\tat android.os.Looper.loop(Looper.java:319)\n\tat android.app.ActivityThread.main(ActivityThread.java:8919)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)\n","STACK_TRACE_HASH":"449303b9","INITIAL_CONFIGURATION":{"colorMode":5,"densityDpi":450,"fontScale":1,"fontWeightAdjustment":0,"hardKeyboardHidden":"HARDKEYBOARDHIDDEN_YES","keyboard":"KEYBOARD_NOKEYS","keyboardHidden":"KEYBOARDHIDDEN_NO","locale":"en_GB","mcc":262,"mnc":7,"navigation":"NAVIGATION_NONAV","navigationHidden":"NAVIGATIONHIDDEN_YES","orientation":"ORIENTATION_PORTRAIT","screenHeightDp":789,"screenLayout":"SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_YES+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO","screenWidthDp":384,"semButtonShapeEnabled":0,"semDesktopModeEnabled":-1,"semDisplayDeviceType":-1,"semMobileKeyboardCovered":-1,"seq":2831,"smallestScreenWidthDp":384,"touchscreen":"TOUCHSCREEN_FINGER","uiMode":"UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_YES","userSetLocale":false},"CUSTOM_DATA":{"Signed-By":"Not signed"},"TOTAL_MEM_SIZE":113613209600,"AVAILABLE_MEM_SIZE":8870547456,"APP_VERSION_CODE":84,"IS_SILENT":false,"USER_APP_START_DATE":"2024-06-19T10:30:28.767+02:00","USER_CRASH_DATE":"2024-06-19T10:30:38.256+02:00","BUILD":{"BOARD":"s5e8835","BOOTLOADER":"A546BXXS8CXE2","BRAND":"samsung","CPU_ABI":"arm64-v8a","CPU_ABI2":"","DEVICE":"a54x","DISPLAY":"UP1A.231005.007.A546BXXS8CXE2","FINGERPRINT":"samsung\/a54xnaeea\/a54x:14\/UP1A.231005.007\/A546BXXS8CXE2:user\/release-keys","HARDWARE":"s5e8835","HOST":"21DKG913","ID":"UP1A.231005.007","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"samsung","MODEL":"SM-A546B","ODM_SKU":"unknown","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"a54xnaeea","RADIO":"unknown","SKU":"unknown","SOC_MANUFACTURER":"Samsung","SOC_MODEL":"s5e8835","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":["arm64-v8a"],"SUPPORTED_ABIS":["arm64-v8a","armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1715073052000,"TYPE":"user","UNKNOWN":"unknown","USER":"dpi","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"samsung\/a54xnaeea\/a54x:14\/UP1A.231005.007\/A546BXXU7CXDC:user\/release-keys","CODENAME":"REL","INCREMENTAL":"A546BXXS8CXE2","KNOWN_CODENAMES":"{HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, UpsideDownCake, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}","MEDIA_PERFORMANCE_CLASS":0,"PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"14","RELEASE_OR_CODENAME":"14","RELEASE_OR_PREVIEW_DISPLAY":"14","SDK":"34","SDK_INT":34,"SECURITY_PATCH":"2024-05-01","SEM_FIRST_SDK_INT":33,"SEM_INT":3401,"SEM_PLATFORM_INT":150100}},"BUILD_CONFIG":{},"CRASH_CONFIGURATION":{"colorMode":5,"densityDpi":450,"fontScale":1,"fontWeightAdjustment":0,"hardKeyboardHidden":"HARDKEYBOARDHIDDEN_YES","keyboard":"KEYBOARD_NOKEYS","keyboardHidden":"KEYBOARDHIDDEN_NO","locale":"en_GB","mcc":262,"mnc":7,"navigation":"NAVIGATION_NONAV","navigationHidden":"NAVIGATIONHIDDEN_YES","orientation":"ORIENTATION_PORTRAIT","screenHeightDp":789,"screenLayout":"SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_YES+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO","screenWidthDp":384,"semButtonShapeEnabled":0,"semDesktopModeEnabled":-1,"semDisplayDeviceType":-1,"semMobileKeyboardCovered":-1,"seq":2976,"smallestScreenWidthDp":384,"touchscreen":"TOUCHSCREEN_FINGER","uiMode":"UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_YES","userSetLocale":false},"REPORT_ID":"3f9ff720-2af7-46b3-a34e-7213da196aa7","PHONE_MODEL":"SM-A546B","ANDROID_VERSION":"14","BRAND":"samsung","FILE_PATH":"\/data\/user\/0\/com.hardbacknutter.nevertoomanybooks\/files","DISPLAY":{"0":{"currentSizeRange":{"smallest":[1080,970],"largest":[2260,2218]},"flags":"FLAG_SUPPORTS_PROTECTED_BUFFERS+FLAG_SECURE","metrics":{"density":2.8125,"densityDpi":450,"scaledDensity":"x2.8125","widthPixels":1080,"heightPixels":2218,"xdpi":403.4110107421875,"ydpi":401.593994140625},"realMetrics":{"density":2.8125,"densityDpi":450,"scaledDensity":"x2.8125","widthPixels":1080,"heightPixels":2340,"xdpi":403.4110107421875,"ydpi":401.593994140625},"name":"Built-in Screen","realSize":[1080,2340],"rectSize":[0,0,1080,2218],"size":[1080,2218],"rotation":"ROTATION_0","isValid":true,"orientation":0,"refreshRate":60,"height":2218,"width":1080,"pixelFormat":1}},"SHARED_PREFERENCES":{"default":{"fields.update.usage.goodreads_book_id":3,"camera.image.action":"1","startup.startCount":6,"fields.update.usage.lt_book_id":3,"ui.theme":"0","fields.update.usage.series_list":2,"scan.mode.single":"1","fields.update.usage.publisher_list":2,"fields.visibility.loaned_to":true,"search.site.isfdb.alted.enabled":true,"startup.startCountdown":5,"fields.visibility":9223372036854775807,"bookList.style.current":"ad55ebc3-f79d-4cc2-a27d-f06ff0bf2335","search.site.bol.data.enabled":true,"fields.update.usage.format":1,"ui.dialog.mode":"2","search.reformat.color":true,"search.site.kbnl.covers.enabled":true,"edit.book.isbn.checks":"1","search.siteOrder.covers":"openlibrary,amazon,isfdb,kbnl","booklist.fastscroller.overlay":"3","fields.update.usage.description":1,"fields.update.usage.print_run":1,"search.site.bedetheque.data.enabled":true,"search.site.googlebooks.data.enabled":true,"fields.update.usage.toc_list":2,"fields.update.usage.bdt_book_id":3,"search.site.lastdodo.data.enabled":true,"ui.menu.context.mode":"2","fields.update.usage.color":1,"edit.book.tab.externalId":false,"search.site.openlibrary.covers.enabled":true,"search.site.openlibrary.data.enabled":true,"search.reformat.format":true,"fields.update.usage.pages":1,"search.site.amazon.data.enabled":true,"search.site.kbnl.data.enabled":true,"fields.update.usage.isbn":1,"sounds.scan.isbn.invalid":true,"camera.lens.facing":"-1","search.site.amazon.covers.enabled":true,"scan.queue":"","fields.update.usage.si_book_id":3,"sort.title.reordered":true,"fields.update.usage.genre":1,"fields.update.usage.ld_book_id":3,"search.siteOrder.data":"openlibrary,isfdb,amazon,googlebooks,stripinfo,lastdodo,stripweb,bedetheque,kbnl,bol","booklist.context.menu":"0","sounds.scan.isbn.valid":false,"fields.update.usage.thumbnail.1":1,"fields.update.usage.thumbnail.0":1,"search.site.isfdb.covers.enabled":true,"booklist.rebuild.state":"0","search.site.stripweb.data.enabled":true,"fields.update.usage.isfdb_book_id":3,"search.site.isfdb.data.enabled":true,"search.site.openlibrary.alted.enabled":true,"backup.last.date":"2024-06-17T14:47:11.872907","fields.update.usage.language":1,"fields.update.usage.title":1,"fields.update.usage.ol_book_id":3,"fields.update.usage.date_published":1,"ui.locale":"system","sounds.scan.barcode.found":true,"network.allow.metered":true,"search.site.stripinfo.data.enabled":true,"camera.image.autorotate":"0","image.cache.resized":true,"fields.update.usage.first_publication":1,"startup.backupCountdown":1,"fields.update.usage.list_price":1,"storage.volume.index":"0","image.undo.enabled":true,"fields.update.usage.author_list":2,"Bookshelf.CurrentBookshelf":"All Books","ui.theme.color":"0","search.siteOrder.alted":"openlibrary,isfdb"}},"ENVIRONMENT":{"getDataDirectory":"\/data","getDataSystemDirectory":"\/data\/system","getDownloadCacheDirectory":"\/data\/cache","getExternalStorageDirectory":"\/storage\/emulated\/0","getExternalStorageState":"mounted","getInternalMediaDirectories":"[\/system\/media, \/oem\/media, \/product\/media, \/omr\/res, \/data\/overlays\/media]","getLegacyExternalStorageDirectory":"\/sdcard","getOdmDirectory":"\/odm","getOemDirectory":"\/oem","getProductDirectory":"\/product","getProductServicesDirectory":"\/product_services","getRootDirectory":"\/system","getStorageDirectory":"\/storage","getSystemExtDirectory":"\/system_ext","getVendorDirectory":"\/vendor","isExternalStorageEmulated":true,"isExternalStorageLegacy":false,"isExternalStorageManager":false,"isExternalStorageRemovable":false},"THREAD_DETAILS":"N\/A","APPLICATION_LOG":"N\/A"}
```

**Comment by tfonteyn** [comment]
java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.Comparable.compareTo(java.lang.Object)' on a null object reference
at java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:320)
at java.util.ComparableTimSort.sort(ComparableTimSort.java:202)
at java.util.Arrays.sort(Arrays.java:1128)
at java.util.Arrays.sort(Arrays.java:1334)
at java.util.ArrayList.sort(ArrayList.java:1738)
at java.util.Collections.sort(Collections.java:210)
at java.util.Collections.sort(Collections.java:163)
at com.hardbacknutter.nevertoomanybooks.dialogs.entities.EditLenderViewModel.getContacts(Unknown Source:161)
at com.hardbacknutter.nevertoomanybooks.dialogs.entities.EditLenderDelegate.addContacts(Unknown Source:116)
at com.hardbacknutter.nevertoomanybooks.dialogs.entities.EditLenderDelegate.onViewCreated(Unknown Source:102)
at com.hardbacknutter.nevertoomanybooks.dialogs.entities.EditLenderDelegate.onViewCreated(Unknown Source:56)
at com.hardbacknutter.nevertoomanybooks.dialogs.BaseBottomSheetDialogFragment.onViewCreated(Unknown Source:92)
at com.hardbacknutter.nevertoomanybooks.dialogs.entities.EditLenderBottomSheet.onViewCreated(Unknown Source:55)    

notes...

Two possibilities:
- "somehow" a null loanee ended up in the private lenders table. Need to double check, but I don't think this is (theoretically) possible in the code. Could be wrong obviously.

- android contacts list returned a null entry; quite possible. The contacts list depends on the actual Contacts app in use on the device. That app could return buggy info.

**Comment by tfonteyn** [comment]
Hello,

I cannot reproduce this.
However, it will be easy to add defensive code so this will not happen again.

I'll prepare a new release later today and let you know here when done.

**Comment by tfonteyn** [comment]
and here you go:  [6.1.3](https://github.com/tfonteyn/NeverTooManyBooks/releases/download/v6.1.3/NeverTooManyBooks-6.1.3.apk)

**Comment by frieda21** [comment]
Thank you it's fixed <3 (and thank you for your work)
